project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!contents/z_ideas/"

website:
  title: "Reproducibility rules in economics"
  description: "A website for the Reproducibility Workshop at the Applied Economics Department of the University of Minnesota, 2026."
  navbar:
    background: primary
    # right: 
    #   - icon: github
    #     href: https://github.com/Shunkei3/Reproducibility-Workshop
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - text: Home
        href: contents/index.qmd
      - section: "Workshop materials"
        contents:
          - text: Session 1
            href: contents/Day1/day1.qmd
          - text: Session 2
            href: contents/Day2/day2.qmd
      - section: "Appendix"
        contents:
          - text: How to use R on VS Code
            href: contents/Appendix1/how-to-radian.qmd






format:
  html:
    theme: [cosmo, flatly, assets/css/theme.scss]
    # theme:  
    #   light: [cosmo, flatly, assets/css/theme.scss]
    #   dark: [cosmo, darkly,  assets/css/theme.scss]
    # mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

# callout-appearance: simple

# execute:
#   freeze: auto



