---
title: "Welcome!"
---

<br>

## {{< fa scroll >}} Workshop Description

The goal of this workshop is to provide best practices for reproducibility in scientific research, and to expand students' practical toolbox to accomplish high-quality reproducibility in their research projects. The workshop consists of two sessions. The first session covers foundational practices such as data management, code organization, and documentation standards aligned with leading journals. The goal of the first session is to review the key components of reproducibility and to experience the reproducible workflow with an example project. Built on the foundations of the first session, the second session dives into more detailed applications and advanced workflow strategies. Topics include preparing replication packages, reference management, writing manuscript with Quarto. Together, the sessions provide practical tools to help students ensure their research meets evolving standards in academia.

<br>

## {{< fa pencil >}} Learning Objectives

By completing the workshop, you will be able to

- Understand the core practices for reproducibility in scientific research.
- Understand the tools and resources available to support reproducibility in research projects.
- Apply best practices for reproducibility in your own research projects, including data management, code organization, and documentation standards.

<br>

## {{< fa clipboard-list >}} In preparation for the workshop

+ Bring your laptop to the class.
+ Make sure you have R and R Studio installed on your laptop. To do this, follow the procedure described in [this website](https://posit.co/download/rstudio-desktop/)
+ Install the **Desktop Zotero** app on your laptop. You can download it from this [official website](https://www.zotero.org/download/). Also, install the **Zotero Connector extension** for your web browser (e.g., Chrome, Firefox, Edge, etc.). This allows you to save references directly from your browser to your Zotero library.
+ Install the **Quarto CLI** on your laptop. You can download it from this [official website](https://quarto.org/docs/get-started/). 

<br>

## {{< fa asterisk >}} Recommended readings

+ [{{< fa book-open >}} Reproducible Research Guide - UC Davis Library](https://ucdavisdatalab.github.io/guide_reproducible_research/chapters/01_principles.html)

+ [{{< fa book-open >}} Data and Code Availability Policy - American Economic Review](https://www.aeaweb.org/journals/data/data-code-policy)
